name: deploy-github-pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo build
        run: cargo build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site' # The directory where your static files live
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
